zk-kk-km:
  image: mshauneu/zookeeper-kafka-manager
  restart: always
  mem_limit: 1G
  ports:
    - "2181:2181"
    - "9092:9092"
    - "9093:9093"
    - "9094:9000"
  environment:
    JMX_PORT: 9093
    ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
  volumes:
    - ./data/zk:/var/lib/zookeeper
    - ./data/kafka:/tmp/kafka-logs
