zookeeper:
  image: wurstmeister/zookeeper
  hostname: zookeeper
  restart: always
  mem_limit: 2G
  ports:
    - "2181:2181"

kafka:
  image: wurstmeister/kafka
  hostname: kafka
  restart: always
  mem_limit: 16G
  ports:
    - "9092:9092"
  environment:
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_ADVERTISED_HOST_NAME: localhost
    KAFKA_ADVERTISED_PORT: 9092
  links:
    - zookeeper:zookeeper

km:
  image: sheepkiller/kafka-manager
  hostname: kafka
  restart: always
  mem_limit: 2G
  ports:
    - "9000:9000"
  environment:
    ZK_HOSTS: zookeeper:2181
    APPLICATION_SECRET: tractionboard
  links:
    - zookeeper:zookeeper
